# Site Settings
paginate:            7

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-feed]

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
style: :compressed
