# Site Settings

paginate:            7

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate, jekyll-feed]

site.github.url: https://tbolt.space
