title:  Teebolt
tagline:  UI Design + Web Development
author:
  name: "Tyler Bolchoz"
  twitter:  tbolt

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/tbolt'}
- {icon: 'twitter', link: 'https://twitter.com/tbolt'}
- {icon: 'envelope', link: 'mailto:tybolt@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
